name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AZURE_WEBAPP_NAME: app-scus-cuusa-web-001
  AZURE_RESOURCE_GROUP: rg-scus-cuusa-web-001

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci --production

      - run: zip -r deploy.zip . -x "*.git*" "**/.git/**" "*.env*" "README.md" ".github/**"

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48CB96D8FD9D41B6BB8D0F2975C51DAC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D08DD9B6251433F9A89FA707502C253 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_015A1106D1A148A081EE39158055B1BF }}

      - name: Deploy & Force New Package
        run: |
          az webapp deploy \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --src-path deploy.zip \
            --type zip \
            --clean true

          az webapp restart --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }}